### ISSUE TITLE
Best attempt to make the most unmaintainable discord bot.

### ISSUE THREAD

**Issue by bluefield-creator** [SK-Fast/polytoria-api-discord-bot#3]
Just to say a few things:

- Mixture of ES5 and ES6 syntax
- Axios and Fetch
- Weird unneeded imports
- Useless code and functions
- Bloated code everywhere
- Use of async and await aswell as promises together
- Use of over 20 packages to do a single function
- variable naming varies more than the variables themselves

Im not sure who'd use this.

**Comment by SK-Fast** [comment]
ya i've planned to fix those in the future
- about the mixure idk i will look into it soon
- axios yea useless am gonna delet it i gues
- some import is from template, gonna delet it if i hav time lul
- ya
- ik but im too dumb so im gonna change it from callback to await aync latr
- some packages are from the module/something that might used in the future so yea
- my brain are wasted and idk how to name that

all of it im goin to fix it soon

**Comment by bluefield-creator** [comment]
We've forked this on polytoria org
